services:
  api:
    image: ghcr.io/tristanduncombe/deco3500-api:latest
    container_name: deco_api
    depends_on:
      db:
        condition: service_healthy
    environment:
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=postgresql+psycopg://postgres:postgres@db:5432/deco
    ports:
      - "8000:8000"
    volumes:
      - api_images:/app/images
    restart: unless-stopped

  ui:
    image: ghcr.io/tristanduncombe/deco3500-ui:latest
    container_name: deco_ui
    depends_on:
      - api
    environment:
      # For server-side fetches inside the container use internal service name
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:8000
      # If you deploy behind a domain, override with public URL
      - NODE_ENV=production
    ports:
      - "3000:3000"
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    container_name: deco_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=deco
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 5s
    restart: unless-stopped

volumes:
  api_images:
  db_data:
